// <auto-generated />
using Backend.MilkApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MilkApp.Migrations
{
    [DbContext(typeof(MilkContext))]
    [Migration("20230125150530_InitialMigrationTwentyOne")]
    partial class InitialMigrationTwentyOne
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Backend.MilkApp.Models.Product", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("storage")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            id = "301d5dcf-a2a8-4a34-b26b-efcaa103963c",
                            name = "Dillion's unequaled cashew milk",
                            storage = 99,
                            type = "Cashew milk"
                        },
                        new
                        {
                            id = "1277e861-b33b-485d-b86f-400769d25a82",
                            name = "Monet's powerful cashew milk",
                            storage = 27,
                            type = "Cashew milk"
                        },
                        new
                        {
                            id = "210aeed2-413b-4e53-98e7-62c9f6fd31ba",
                            name = "Julianne's relevant pea milk",
                            storage = 33,
                            type = "Pea milk"
                        },
                        new
                        {
                            id = "72204ea0-29e2-4da8-bf57-648b37268b71",
                            name = "Macie's broad walnut milk",
                            storage = 23,
                            type = "Walnut milk"
                        },
                        new
                        {
                            id = "06d60157-e9c7-4bd9-b2a6-00fd63bb2033",
                            name = "Christa's fearful rice milk",
                            storage = 46,
                            type = "Rice milk"
                        },
                        new
                        {
                            id = "6905f2f6-e80c-4601-8ae6-5408485ef9c5",
                            name = "Shakayla's loose coconut milk",
                            storage = 82,
                            type = "Coconut milk"
                        },
                        new
                        {
                            id = "10aed344-837d-4621-873e-aeac9394c99f",
                            name = "Duane's salty soy milk",
                            storage = 24,
                            type = "Soy milk"
                        },
                        new
                        {
                            id = "2ceec543-8fd9-4c7c-855a-c1388a68ca78",
                            name = "Deangelo's rotten hemp milk",
                            storage = 59,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "dd9140c5-af1d-4861-9736-e0b4f4a81bb7",
                            name = "Gaven's numberless walnut milk",
                            storage = 89,
                            type = "Walnut milk"
                        },
                        new
                        {
                            id = "0798ae22-c922-4b47-adc5-23feac38020f",
                            name = "Tea's scientific rice milk",
                            storage = 15,
                            type = "Rice milk"
                        },
                        new
                        {
                            id = "3dbf9e44-fb2f-487b-8b34-7e6e6700e17e",
                            name = "Cora's early almond milk",
                            storage = 58,
                            type = "Almond milk"
                        },
                        new
                        {
                            id = "ea1aadc3-bd1e-4f43-a46d-e035e7a96282",
                            name = "Jonah's aware cashew milk",
                            storage = 79,
                            type = "Cashew milk"
                        },
                        new
                        {
                            id = "1bba8dfc-07af-414d-b85d-663443612e5b",
                            name = "Catrina's fallacious almond milk",
                            storage = 62,
                            type = "Almond milk"
                        },
                        new
                        {
                            id = "2534898d-223e-49f8-9a4f-2993458fc5f2",
                            name = "Kristian's quickest oat milk",
                            storage = 37,
                            type = "Oat milk"
                        },
                        new
                        {
                            id = "3989e76f-0546-4b01-bad6-5d52535e8136",
                            name = "Jessi's unbiased almond milk",
                            storage = 76,
                            type = "Almond milk"
                        },
                        new
                        {
                            id = "fe7c5123-4141-427e-92ed-e9b41bf88c2a",
                            name = "Jean's wide hemp milk",
                            storage = 90,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "b3a8ed8d-be54-40b7-9880-5e7df192b981",
                            name = "Stephen's torpid walnut milk",
                            storage = 26,
                            type = "Walnut milk"
                        },
                        new
                        {
                            id = "d6e96a38-ce76-42d9-95a4-7247ea4dcb7a",
                            name = "Christa's squealing cashew milk",
                            storage = 100,
                            type = "Cashew milk"
                        },
                        new
                        {
                            id = "b48a9bbd-ef6b-4205-8c06-014e891a9faf",
                            name = "Dominik's fearful oat milk",
                            storage = 25,
                            type = "Oat milk"
                        },
                        new
                        {
                            id = "352139db-6f31-4856-83eb-4142c92a3c44",
                            name = "Joshua's full macadamia milk",
                            storage = 44,
                            type = "Macadamia milk"
                        },
                        new
                        {
                            id = "3e437e24-8d75-4063-acbf-827d3c833d90",
                            name = "Judith's orange cashew milk",
                            storage = 85,
                            type = "Cashew milk"
                        },
                        new
                        {
                            id = "283ff036-d83d-403c-8a67-b25f1c096682",
                            name = "Kentrell's unequaled whole milk",
                            storage = 51,
                            type = "Whole milk"
                        },
                        new
                        {
                            id = "7786da9f-efb9-4e4d-828b-3cf85f1e63c6",
                            name = "Kristian's wealthy cashew milk",
                            storage = 11,
                            type = "Cashew milk"
                        },
                        new
                        {
                            id = "e554d358-ec1c-4b9b-97a3-97fa999abb64",
                            name = "Dominik's alive whole milk",
                            storage = 97,
                            type = "Whole milk"
                        },
                        new
                        {
                            id = "3f2a611a-4d0b-41e1-8165-2f8f9a1f66aa",
                            name = "Jean's scared coconut milk",
                            storage = 25,
                            type = "Coconut milk"
                        },
                        new
                        {
                            id = "fd2349a0-3d48-4d9b-ac22-6290d1053495",
                            name = "Sheldon's tasteless cashew milk",
                            storage = 80,
                            type = "Cashew milk"
                        },
                        new
                        {
                            id = "e80064ce-5599-46f6-a2d9-6bc7a1aca872",
                            name = "Jocelyn's rough soy milk",
                            storage = 25,
                            type = "Soy milk"
                        },
                        new
                        {
                            id = "9466032f-db34-49d3-9ae3-7385cc0082f7",
                            name = "Chandler's full oat milk",
                            storage = 32,
                            type = "Oat milk"
                        },
                        new
                        {
                            id = "d84696a9-600d-4912-914d-bbb7f6a5e744",
                            name = "Tea's wide pea milk",
                            storage = 40,
                            type = "Pea milk"
                        },
                        new
                        {
                            id = "50045980-f3c9-408b-83bf-a98db403d42d",
                            name = "Dillion's taboo hemp milk",
                            storage = 58,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "81bd9a68-5599-4018-990a-694b519a9bdb",
                            name = "Korbin's open pea milk",
                            storage = 94,
                            type = "Pea milk"
                        },
                        new
                        {
                            id = "7be33cd3-311a-4418-a24d-a501c8d31465",
                            name = "Stephen's fearful macadamia milk",
                            storage = 100,
                            type = "Macadamia milk"
                        },
                        new
                        {
                            id = "d2f12e7b-f096-4391-ad72-b4517deb24cf",
                            name = "Jessalyn's fallacious almond milk",
                            storage = 65,
                            type = "Almond milk"
                        },
                        new
                        {
                            id = "50a70194-f239-43f6-81de-25628b27ea5a",
                            name = "Jaeden's cooing cashew milk",
                            storage = 33,
                            type = "Cashew milk"
                        },
                        new
                        {
                            id = "0ac95b83-bdce-497c-b0c3-7c0071419324",
                            name = "Christa's wealthy whole milk",
                            storage = 84,
                            type = "Whole milk"
                        },
                        new
                        {
                            id = "ff6524a8-ab9c-4320-8c41-17e3a8da268e",
                            name = "Judith's bumpy almond milk",
                            storage = 66,
                            type = "Almond milk"
                        },
                        new
                        {
                            id = "9001c051-305d-462c-aefb-be220eadae6b",
                            name = "Jaquez's unequaled hemp milk",
                            storage = 76,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "0037a064-7ce1-4c97-b8a0-51848775a7a9",
                            name = "Elliot's recent almond milk",
                            storage = 50,
                            type = "Almond milk"
                        },
                        new
                        {
                            id = "9811f876-ebc9-44f0-88ae-1d087cb940db",
                            name = "Brittney's unbiased coconut milk",
                            storage = 96,
                            type = "Coconut milk"
                        },
                        new
                        {
                            id = "179670c3-e49f-4655-ab71-12a90b912cc5",
                            name = "Dillion's rough rice milk",
                            storage = 56,
                            type = "Rice milk"
                        },
                        new
                        {
                            id = "602d410e-46e1-4744-9b82-cfc7dd5d0940",
                            name = "Lucero's wholesale whole milk",
                            storage = 46,
                            type = "Whole milk"
                        },
                        new
                        {
                            id = "aa5ce91a-67e6-4349-b1c2-4c4050efb49e",
                            name = "Jedidiah's early almond milk",
                            storage = 49,
                            type = "Almond milk"
                        },
                        new
                        {
                            id = "78b2fb8e-4c91-439e-a479-f8c1e9595343",
                            name = "Kasey's quickest hemp milk",
                            storage = 4,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "1d52f5a1-4c39-4352-85df-168320fb3575",
                            name = "Kasey's wide rice milk",
                            storage = 54,
                            type = "Rice milk"
                        },
                        new
                        {
                            id = "2f1ce24b-9536-4988-a8b5-c7d9334b74ce",
                            name = "Judith's steady pea milk",
                            storage = 32,
                            type = "Pea milk"
                        },
                        new
                        {
                            id = "d3ba0a73-29a1-4802-b284-a498df060c42",
                            name = "Benjamin's taboo soy milk",
                            storage = 87,
                            type = "Soy milk"
                        },
                        new
                        {
                            id = "1dda5869-263d-460c-8275-3b131e17c601",
                            name = "Gaven's early cashew milk",
                            storage = 36,
                            type = "Cashew milk"
                        },
                        new
                        {
                            id = "7d1d6d3d-160c-4461-9b93-385041a224a2",
                            name = "Kentrell's loose hemp milk",
                            storage = 79,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "a3df7049-9b81-476d-a803-e8ed8aca161a",
                            name = "Johnny's second whole milk",
                            storage = 54,
                            type = "Whole milk"
                        },
                        new
                        {
                            id = "2356a84e-0fbb-4b5b-993c-0bc6c70586e2",
                            name = "Quincy's whole soy milk",
                            storage = 10,
                            type = "Soy milk"
                        },
                        new
                        {
                            id = "b1b4f84b-57f2-420a-9506-ac0636935ab0",
                            name = "Kasey's painful pea milk",
                            storage = 62,
                            type = "Pea milk"
                        },
                        new
                        {
                            id = "99370f4e-7b31-4d0f-94ab-bd6dae094ddb",
                            name = "Nehemiah's salty hemp milk",
                            storage = 4,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "27ebf833-e1ba-40a6-b101-da4eb71313d8",
                            name = "Jonah's second hemp milk",
                            storage = 26,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "264a505c-4d88-4a61-966c-471d5233d8d1",
                            name = "Korbin's fearful walnut milk",
                            storage = 27,
                            type = "Walnut milk"
                        },
                        new
                        {
                            id = "62603a88-f96f-4beb-a0ed-98358826974a",
                            name = "Deangelo's onerous walnut milk",
                            storage = 57,
                            type = "Walnut milk"
                        },
                        new
                        {
                            id = "697a783b-43e4-478e-bd1b-253676e43c0b",
                            name = "Joshua's existing rice milk",
                            storage = 73,
                            type = "Rice milk"
                        },
                        new
                        {
                            id = "1fcb5bbb-0fa4-40d5-92ae-0e751c18d704",
                            name = "Lincoln's scared walnut milk",
                            storage = 71,
                            type = "Walnut milk"
                        },
                        new
                        {
                            id = "ad3bf06b-9c2d-4c3e-8fdd-d0fec4ef99b6",
                            name = "Kentrell's rough almond milk",
                            storage = 40,
                            type = "Almond milk"
                        },
                        new
                        {
                            id = "1627d6d8-1a96-4011-8294-49b9f1e90ba8",
                            name = "Kentrell's scientific macadamia milk",
                            storage = 1,
                            type = "Macadamia milk"
                        },
                        new
                        {
                            id = "886fa2ee-e61f-42e8-8f90-80d46f792924",
                            name = "Catrina's aware macadamia milk",
                            storage = 64,
                            type = "Macadamia milk"
                        },
                        new
                        {
                            id = "0597329f-b2fb-49a9-a5fd-13797fa1d7ce",
                            name = "Marion's torpid soy milk",
                            storage = 41,
                            type = "Soy milk"
                        },
                        new
                        {
                            id = "63937d8a-aaf5-46b4-a997-f78eda7b6157",
                            name = "Harlie's squealing pea milk",
                            storage = 47,
                            type = "Pea milk"
                        },
                        new
                        {
                            id = "95992ab8-183a-4e19-b404-970e24d5300a",
                            name = "Elliot's unbiased pea milk",
                            storage = 48,
                            type = "Pea milk"
                        },
                        new
                        {
                            id = "df679bb2-a8b0-41af-a291-02b28c10c4ff",
                            name = "Tea's strong hemp milk",
                            storage = 19,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "ce87d24d-e70d-4b21-961c-addc7162f792",
                            name = "Nehemiah's wealthy cashew milk",
                            storage = 35,
                            type = "Cashew milk"
                        },
                        new
                        {
                            id = "38730f3c-009e-4873-995e-7a023a8f759f",
                            name = "Judith's quickest oat milk",
                            storage = 84,
                            type = "Oat milk"
                        },
                        new
                        {
                            id = "77afcf09-4b31-445d-b33d-66e197dcbdd0",
                            name = "Karlee's painful rice milk",
                            storage = 55,
                            type = "Rice milk"
                        },
                        new
                        {
                            id = "e250de50-a606-49d9-afa7-fa118c9a3184",
                            name = "Joshua's rotten oat milk",
                            storage = 15,
                            type = "Oat milk"
                        },
                        new
                        {
                            id = "52c82b59-042b-4b40-8c12-6475156cc87e",
                            name = "Kristian's bumpy pea milk",
                            storage = 33,
                            type = "Pea milk"
                        },
                        new
                        {
                            id = "ba46543f-2bd3-449e-8e62-ee6f269bfc10",
                            name = "Jonah's early hemp milk",
                            storage = 44,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "9373d575-0d21-4e11-80d6-e7e35a836f28",
                            name = "Stephen's wealthy hemp milk",
                            storage = 34,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "9a2bfc2f-2a8f-4a62-92b0-dcdcca37bba2",
                            name = "Felicity's second cashew milk",
                            storage = 76,
                            type = "Cashew milk"
                        },
                        new
                        {
                            id = "a83d309f-ebe5-4bed-9555-bc18869d98ca",
                            name = "Elliot's voiceless cashew milk",
                            storage = 87,
                            type = "Cashew milk"
                        },
                        new
                        {
                            id = "41916cd4-9d74-4222-9fa8-114a2d3a64ce",
                            name = "Zain's wealthy cashew milk",
                            storage = 71,
                            type = "Cashew milk"
                        },
                        new
                        {
                            id = "48029d08-8dcb-486e-8cc8-86961f8658dc",
                            name = "Dominik's rough whole milk",
                            storage = 83,
                            type = "Whole milk"
                        },
                        new
                        {
                            id = "34a5ceb6-0c67-4794-936b-db67c5ff9109",
                            name = "Karlee's rough soy milk",
                            storage = 99,
                            type = "Soy milk"
                        },
                        new
                        {
                            id = "7cb2ff70-98b4-4735-8cc0-25bc2d37ad44",
                            name = "Tyquan's wholesale almond milk",
                            storage = 21,
                            type = "Almond milk"
                        },
                        new
                        {
                            id = "ffd3b484-ede9-43da-aad8-d4d318438d7d",
                            name = "Cora's loose pea milk",
                            storage = 70,
                            type = "Pea milk"
                        },
                        new
                        {
                            id = "2ce0972a-915a-4f42-afe9-09e9364c9668",
                            name = "Catrina's fallacious coconut milk",
                            storage = 54,
                            type = "Coconut milk"
                        },
                        new
                        {
                            id = "6774d933-12ec-4db4-ac3e-215e817a4a56",
                            name = "Judith's rotten rice milk",
                            storage = 43,
                            type = "Rice milk"
                        },
                        new
                        {
                            id = "2ef1b9a2-870b-4b78-87c1-1d73070c4cd4",
                            name = "Jedidiah's cumbersome oat milk",
                            storage = 16,
                            type = "Oat milk"
                        },
                        new
                        {
                            id = "b6679277-32a8-4d7c-9e19-2799aa9a3fb3",
                            name = "Karlee's tan oat milk",
                            storage = 39,
                            type = "Oat milk"
                        },
                        new
                        {
                            id = "4f183948-3744-4e9e-8907-c6f10644cfbf",
                            name = "Johnny's quickest rice milk",
                            storage = 41,
                            type = "Rice milk"
                        },
                        new
                        {
                            id = "f6e801ff-336e-4aa7-879b-13b16bef285f",
                            name = "Samuel's broad soy milk",
                            storage = 33,
                            type = "Soy milk"
                        },
                        new
                        {
                            id = "663da2d8-bde6-4eb6-94a3-01bf4c3f8c4f",
                            name = "Rodney's relevant hemp milk",
                            storage = 56,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "4e46d68b-cd90-4549-8f49-644fd4fe7a61",
                            name = "Joan's numberless soy milk",
                            storage = 98,
                            type = "Soy milk"
                        },
                        new
                        {
                            id = "4500a34b-e06e-4a5f-89fd-7804611e9e51",
                            name = "Tea's alive almond milk",
                            storage = 55,
                            type = "Almond milk"
                        },
                        new
                        {
                            id = "33f05a1b-de2e-4319-b279-2313478dd891",
                            name = "Duane's typical walnut milk",
                            storage = 89,
                            type = "Walnut milk"
                        },
                        new
                        {
                            id = "85a307d1-3af5-410a-8cfa-31489fdc9df1",
                            name = "Benjamin's scared whole milk",
                            storage = 4,
                            type = "Whole milk"
                        },
                        new
                        {
                            id = "87704f41-8529-4268-aaad-5c20023d0db6",
                            name = "Jaquez's whole oat milk",
                            storage = 50,
                            type = "Oat milk"
                        },
                        new
                        {
                            id = "f8021d2c-c37a-4e62-afe6-02487057cc3b",
                            name = "Kerry's unbiased whole milk",
                            storage = 21,
                            type = "Whole milk"
                        },
                        new
                        {
                            id = "e0041dbf-13bf-4371-9b2c-ff575492411e",
                            name = "Nehemiah's open almond milk",
                            storage = 23,
                            type = "Almond milk"
                        },
                        new
                        {
                            id = "7fb4ac10-d5ba-4403-85d1-236ccc76b378",
                            name = "Jonah's bumpy hemp milk",
                            storage = 72,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "cc96a41f-bb3a-450c-ae76-683edc71be52",
                            name = "Michele's alive walnut milk",
                            storage = 25,
                            type = "Walnut milk"
                        },
                        new
                        {
                            id = "28327307-f377-4fc4-b497-d85e09552449",
                            name = "Kristian's divergent soy milk",
                            storage = 24,
                            type = "Soy milk"
                        },
                        new
                        {
                            id = "2702fab9-db1c-44bf-a43f-9107cf21e499",
                            name = "Joan's full pea milk",
                            storage = 67,
                            type = "Pea milk"
                        },
                        new
                        {
                            id = "d407b372-2624-4e7b-8e8b-d6b2c1641e5a",
                            name = "Lance's steady walnut milk",
                            storage = 59,
                            type = "Walnut milk"
                        },
                        new
                        {
                            id = "396937ec-6ae7-4a16-977b-de9544c152b1",
                            name = "Sheldon's tasteless hemp milk",
                            storage = 4,
                            type = "Hemp milk"
                        },
                        new
                        {
                            id = "cf5a5299-c4dd-4699-a8d7-1eed6382888b",
                            name = "Kristian's early coconut milk",
                            storage = 35,
                            type = "Coconut milk"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
